CREATE TABLE IF NOT EXISTS USER(
    id INT AUTO_INCREMENT,
    name NVARCHAR(64) NOT NULL UNIQUE,
    password_hash NVARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PHOTO_POST(
    id INT AUTO_INCREMENT,
    description NVARCHAR(1024),
    creation_date DATE NOT NULL,
    src NVARCHAR(256),
    user_id INT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES USER(id)
) ENGINE=INNODB;

